# Generated by Django 4.2.5 on 2023-09-12 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Contry')),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
                ('text', models.TextField(verbose_name='Etrafli')),
                ('shop_img', models.ImageField(blank=True, null=True, upload_to='Shop_img/%Y/%m/%d/', verbose_name='Shop_img')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Price')),
                ('creted_at', models.DateTimeField(auto_now_add=True, verbose_name='Qeyd_tarixi')),
                ('creted_up', models.DateTimeField(auto_now=True, verbose_name='Yenilenme_tarixi')),
                ('public', models.BooleanField(default=True, verbose_name='Derc_edilib')),
                ('contry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.contry', verbose_name='Olke')),
            ],
            options={
                'verbose_name': 'Mehsullar',
                'verbose_name_plural': 'Mehsullar',
            },
        ),
    ]
