# Generated by Django 4.2.5 on 2023-09-17 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Categoriya')),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Categoriya',
                'verbose_name_plural': 'CAtegoriya',
            },
        ),
        migrations.AlterModelOptions(
            name='contry',
            options={'verbose_name': 'Olke', 'verbose_name_plural': 'Olke'},
        ),
        migrations.AddField(
            model_name='shop',
            name='categoriya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Categoriya'),
        ),
    ]
