# Generated by Django 4.2.5 on 2023-09-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='text',
            field=models.TextField(blank=True, verbose_name='Etrafli'),
        ),
    ]
