# Generated by Django 4.2.5 on 2023-09-27 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_shop_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='categoriya',
            field=models.ForeignKey(blank=True, default='Secim edin', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Categoriya'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='contry',
            field=models.ForeignKey(blank=True, default='Secim edin', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.contry', verbose_name='Olke'),
        ),
    ]
